In [ ]:
#Aditya Doke
#A-44

In [23]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

In [24]:
df = pd.read_csv("iris.csv")
df.head()  # Display first 5 rows


sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [25]:
# Check for missing values
print(df.isnull().sum())

# Encode target labels if not already encoded
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
df['species'] = encoder.fit_transform(df['species'])  # Assuming 'species' is the target column


sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64


In [26]:
X = df.iloc[:, :-1]  # Select all columns except the last (features)
y = df.iloc[:, -1]   # Select the last column (target variable)

# Split into train (80%) and test (20%) sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Display shape of train and test sets
print("Training Set Size:", X_train.shape)
print("Testing Set Size:", X_test.shape)


Training Set Size: (120, 4)
Testing Set Size: (30, 4)


In [27]:
nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)


GaussianNB()

In [28]:
y_pred = nb_classifier.predict(X_test)


In [29]:
# Compute Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

# Extract TP, FP, TN, FN
TN, FP, FN, TP = cm.ravel() if cm.shape == (2, 2) else (None, None, None, None)  # Only applicable for binary classification

# Compute Performance Metrics
accuracy = accuracy_score(y_test, y_pred)
error_rate = 1 - accuracy
precision = precision_score(y_test, y_pred, average='macro')  # Use 'macro' for multi-class
recall = recall_score(y_test, y_pred, average='macro')
f1 = f1_score(y_test, y_pred, average='macro')

# Display Metrics
print(f"Accuracy: {accuracy:.2f}")
print(f"Error Rate: {error_rate:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1 Score: {f1:.2f}")


Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Accuracy: 1.00
Error Rate: 0.00
Precision: 1.00
Recall: 1.00
F1 Score: 1.00


In [ ]:
'''
Explanation


🧩 confusion_matrix
A table that shows:
TP (True Positives)
TN (True Negatives)
FP (False Positives)
FN (False Negatives)
Helps you see model performance.

🎯 accuracy_score
% of correct predictions.
Formula:
(TP + TN) / Total

🎯 precision_score
Out of predicted positives, how many were correct?
Formula:
TP / (TP + FP)

🎯 recall_score
Out of actual positives, how many did the model catch?
Formula:
TP / (TP + FN)

🎯 f1_score
A balance between precision and recall.
Used when data is imbalanced.
Formula:
2 * (Precision * Recall) / (Precision + Recall)
'''

